package Sintesis.ProfessorsEscriptori;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class SampleController {
	@FXML
	private ListView alumnes;
	@FXML
	private ListView exercicis;
	@FXML
	private TextField curs;

	// Event Listener on ListView[#alumnes].onMouseClicked
	@FXML
	public void buscaExercicis(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void buscaAlumnes(ActionEvent event) {
		// TODO Autogenerated
	}
}
